name: vEconomy
version: 1.1.0
main: com.vitor.vEconomy
api-version: '1.21'
authors: [SoldadoHumano]
depend: [PlaceholderAPI]
website: https://github.com/SoldadoHumano

commands:
  veconomy:
    description: Comando principal do vEconomy
    usage: /veconomy <args>
    permission: veconomy.admin
    aliases: [economy, veco, eco]
  money:
    description: Comando para ver seu money
    usage: /money <args>
    aliases:
      - bal
      - balance
    permission: vEconomy.balance

permissions:
  vEconomy.admin:
    description: Permissão total para administrar a economia
    default: op
  vEconomy.balance:
    description: Permissão para ver o dinheiro via comando
    default: true